# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4de428ccdaae83185579b362e6500e3b04bd7f4f7d010ee3c2690147abc9ec9ff3124cc036b6e9aa314bc9cf716060705440dde54dd66a7edfe2e8ba9daef0c

test:
  secret_key_base: 6667af656d62559b2c803e2da576d5e01af3843b368753007e6c844a254f6c74f8009418fd53095c562aa30d1f53c4edfe823c08b14a042d125e1729df7428e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
